### ISSUE TITLE
QSW-1108-8T

### ISSUE THREAD

**Issue by Sacro** [danieltwagner/qsw-2104-2s#4]
I'm back again, I'm returning the 5 ports and upgrading to the 8, however the 8 doesn't seem to be on 1.1.1.100, and doesn't seem to have a serial connection point either.

Going to go ARP listening and see if I can find it. 

I've also written the API details into OpenAPI 3 format, in case you or anyone wanted to import it into Insomnia (or other apps)
https://github.com/Sacro/qnap-swagger - feel free to add it to your repo if you wish.

**Comment by Sacro** [comment]
Oh, it's not a Broadcom chip in this, it's a Realtek RTL8371

**Comment by danieltwagner** [comment]
Huh, I wonder if they've moved closer to an architecture like some of these cheaper switches STH has recently reviewed: https://www.servethehome.com/finally-mokerlink-2g08110gs-8x-2-5gbe-1x-10gbe-switch-review/ -- is it a single RTL8371?

**Comment by danieltwagner** [comment]
I have added information about the QSW-1108-8T not being based on Robo2 in the Readme. Thank you for your contribution.
